src/main/default/objects/GraphQLClientConfig__mdt/GraphQLClientConfig__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata containing configuration for the Apex GraphQL Client package</description>
    <label>GraphQL Client Config</label>
    <pluralLabel>GraphQL Client Configs</pluralLabel>
</CustomObject>

src/main/default/objects/GraphQLClientConfig__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>The value of the configuration specified by the custom metadata record name</description>
    <label>Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/test/classes/GraphQLConfigsTest.cls
@IsTest(isParallel = true)
private class GraphQLConfigsTest {
    @IsTest
    private static void getString_shouldReturnStringConfig() {
        GraphQLConfigs.Option config = GraphQLConfigs.Option.DateArgumentFormat;
        GraphQLConfigs.configsByName.put(
            config.name(),
            new GraphQLClientConfig__mdt(DeveloperName = config.name(), Value__c = 'MM/dd/yyyy')
        );

        String configValue = GraphQLConfigs.getString(config);

        System.assert(configValue != null);
        System.assertEquals('MM/dd/yyyy', configValue);
    }

    @IsTest
    private static void getString_configDoesntExist_shouldThrowException() {
        GraphQLConfigs.Option config = GraphQLConfigs.Option.DateArgumentFormat;
        GraphQLConfigs.configsByName.clear();

        Exception error;
        try {
            GraphQLConfigs.getString(config);
        } catch (Exception ex) {
            error = ex;
        }

        System.assert(error != null);
        System.assert(error.getMessage().startsWith('There is no such configuration entry'));
    }
}