src/main/default/objects/GraphQLClientConfiguration__mdt/GraphQLClientConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata containing configuration for the Apex GraphQL Client package</description>
    <label>GraphQL Client Configuration</label>
    <pluralLabel>GraphQL Client Configurations</pluralLabel>
</CustomObject>

src/main/default/objects/GraphQLClientConfiguration__mdt/fields/ConfigurationValue__c.field-meta.xml
<CustomField>
    <fullName>ConfigurationValue__c</fullName>
    <description>The value of the configuration specified by the custom metadata record name</description>
    <label>Configuration Value</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/test/classes/GraphQLConfigurationManagerTest.cls
@IsTest(IsParallel=true)
private class GraphQLConfigurationManagerTest {
    @IsTest
    private static void getConfigurationPositiveTest() {
        String configName = GraphQLConfiguration.DateArgumentFormat.name();
        GraphQLClientConfiguration__mdt dateArgumentFormatConfig = [
            SELECT ConfigurationValue__c
            FROM GraphQLClientConfiguration__mdt
            WHERE DeveloperName = :configName
        ];

        String configValue = GraphQLConfigurationManager.getConfiguration(configName);

        System.assert(configValue != null);
        System.assertEquals(dateArgumentFormatConfig.ConfigurationValue__c, configValue);
    }

    @IsTest
    private static void getConfigurationNegativeTest() {
        String configName = 'FakeConfig';

        String configValue;
        Exception error;
        try {
            configValue = GraphQLConfigurationManager.getConfiguration(configName);
        } catch (Exception ex) {
            error = ex;
        }

        System.assert(configValue == null);
        System.assert(error != null);
        System.assert(error.getMessage().startsWith('There is no such configuration entry'));
    }
}